<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LibraryTargetFrameworks)</TargetFrameworks>
    <RootNamespace>ReactiveUI.Primitives.OccasionallyConnected.Server</RootNamespace>
    <PackageDescription>Server primitives for authenticated occasionally connected synchronization.</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />
    <ProjectReference Include="..\ReactiveUI.Primitives.OccasionallyConnected.Core\ReactiveUI.Primitives.OccasionallyConnected.Core.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <PackageReference Include="Microsoft.Bcl.TimeProvider" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SQLitePCLRaw.core" />
    <PackageReference Include="SQLite3MC.PCLRaw.bundle" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\OccasionallyConnected.Sqlite.Shared\*.cs" Link="Sqlite\%(Filename)%(Extension)" />
    <Compile Include="..\ReactiveUI.Primitives.OccasionallyConnected.Storage.Sqlite\SqliteSynchronousCommandWorker.cs" Link="Sqlite\SqliteSynchronousCommandWorker.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="README.md" />
  </ItemGroup>
</Project>
