<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <RootNamespace>ReactiveUI.Primitives.OccasionallyConnected.Collaboration.Server.Tests</RootNamespace>
    <AssemblyName>ReactiveUI.Primitives.OccasionallyConnected.Collaboration.Server.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\examples\OccasionallyConnected.Collaboration.Server\OccasionallyConnected.Collaboration.Server.csproj" />
    <ProjectReference Include="..\..\ReactiveUI.Primitives.OccasionallyConnected.Transport.Http\ReactiveUI.Primitives.OccasionallyConnected.Transport.Http.csproj" />
  </ItemGroup>

</Project>
