### YamlMime:ManagedReference
ignore:
  - src/tests
  - src/tools
  - src/benchmarks
  - integrationtests
  - "**/tests/"
  - "**/tools/"
  - "**/benchmarks/"
  - "**/Tests/"
  - "**/*.Tests/"
coverage:
  status:
    patch:
      default:
        target: 79.5%
        threshold: 0%
