<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System"/>
    <Using Include="System.Collections.Generic"/>
    <Using Include="System.Diagnostics.CodeAnalysis"/>
    <Using Include="System.Linq"/>
    <Using Include="System.Threading"/>
    <Using Include="System.Threading.Tasks"/>
    <Using Include="TUnit.Core.Executors"/>
    <Using Include="TUnit.Core.Interfaces"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ReactiveUI.Disposables\ReactiveUI.Disposables.csproj"/>
  </ItemGroup>

</Project>
