<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LibraryTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ReactiveUI.Disposables.Tests" />
    <InternalsVisibleTo Include="ReactiveUI.Primitives.Tests" />
    <InternalsVisibleTo Include="ReactiveUI.Primitives.Extensions.Tests" />
    <InternalsVisibleTo Include="ReactiveUI.Primitives.Async.Tests" />
    <InternalsVisibleTo Include="ReactiveUI.Primitives.Blazor.Tests" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Compile Include="..\Polyfills\NotNullAttribute.cs" Link="Polyfills\NotNullAttribute.cs" />
    <Compile Include="..\Polyfills\CallerArgumentExpressionAttribute.cs" Link="Polyfills\CallerArgumentExpressionAttribute.cs" />
    <Compile Include="..\Polyfills\ArgumentExceptionHelper.cs" Link="Polyfills\ArgumentExceptionHelper.cs" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Using Include="ReactiveUI.Primitives.Internal.ArgumentExceptionHelper" Alias="ArgumentExceptionHelper" />
  </ItemGroup>
  <ItemGroup Condition="!$(TargetFramework.StartsWith('net4'))">
    <Using Include="System.ArgumentNullException" Alias="ArgumentExceptionHelper" />
  </ItemGroup>

</Project>
