<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ReactiveUI.Primitives.OccasionallyConnected.Reactive\ReactiveUI.Primitives.OccasionallyConnected.Reactive.csproj" />
  </ItemGroup>

</Project>
