// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

namespace ReactiveUI.Primitives.ObservableEvents.CodeGeneration;

/// <summary>Declares the generic activation placeholder and static-host attribute.</summary>
internal static class ActivationSource
{
    /// <summary>The source text added to every compilation.</summary>
    internal const string Text = """
        // <auto-generated />
        namespace ReactiveUI.Primitives.ObservableEvents
        {
            /// <summary>Requests observable wrappers for public static events on a type.</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
            internal sealed class GenerateStaticEventObservablesAttribute : global::System.Attribute
            {
                /// <summary>Initializes the request.</summary>
                /// <param name="type">The static event host.</param>
                public GenerateStaticEventObservablesAttribute(global::System.Type type) => Type = type;

                /// <summary>Gets the requested static event host.</summary>
                public global::System.Type Type { get; }
            }

            /// <summary>Contains activation extensions used by the observable-event generator.</summary>
            internal static partial class ObservableGeneratorExtensions
            {
                /// <summary>Requests observable wrappers for the receiver's public events.</summary>
                /// <typeparam name="T">The event host type.</typeparam>
                /// <param name="eventHost">The event host.</param>
                /// <returns>A placeholder replaced by a generated, strongly typed overload.</returns>
                public static NullEvents Events<T>(this T eventHost) => default;
            }

            /// <summary>Placeholder returned until a strongly typed event wrapper is generated.</summary>
            internal readonly struct NullEvents
            {
            }
        }
        """;
}
