// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

#if NET8_0 && !NET9_0_OR_GREATER
using System.Diagnostics.CodeAnalysis;
#endif
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.DependencyInjection;

namespace ReactiveUI.Primitives.OccasionallyConnected.SignalR;

/// <summary>Registers the bounded SignalR protocol and maps its hub.</summary>
public static class SignalRServiceCollectionExtensions
{
    /// <summary>The base64 and outer protocol framing safety multiplier.</summary>
    private const long FramingMultiplier = 2;

    /// <summary>The maximum admitted invocations per physical connection.</summary>
    private const int InvocationCapacity = 8;

    /// <summary>Composes the host's SignalR routes.</summary>
    /// <param name="endpoints">The host endpoints.</param>
    extension(IEndpointRouteBuilder endpoints)
    {
        /// <summary>Maps the hub. The host must register a singleton <see cref="SignalRServerEndpoint"/> and authentication.</summary>
        /// <param name="pattern">The hub route.</param>
        /// <returns>The endpoint convention builder for host authorization policies.</returns>
        public HubEndpointConventionBuilder MapOccasionallyConnectedSignalR(string pattern)
        {
            ArgumentNullException.ThrowIfNull(endpoints);
            return endpoints.MapHub<OccasionallyConnectedHub>(pattern, static options =>
            {
                options.ApplicationMaxBufferSize = SignalRCarrier.MaximumBytes * FramingMultiplier;
                options.TransportMaxBufferSize = SignalRCarrier.MaximumBytes * FramingMultiplier;
                options.AllowStatefulReconnects = false;
            });
        }
    }

    /// <summary>Composes the host's SignalR services.</summary>
    /// <param name="services">The host services.</param>
    extension(IServiceCollection services)
    {
        /// <summary>Registers SignalR with generated byte-array JSON metadata and finite hub limits.</summary>
        /// <returns>The SignalR builder for additional host configuration.</returns>
#if NET8_0 && !NET9_0_OR_GREATER
        [RequiresUnreferencedCode("ASP.NET Core 8 SignalR service registration does not support trimming.")]
#endif
        public ISignalRServerBuilder AddOccasionallyConnectedSignalR()
        {
            ArgumentNullException.ThrowIfNull(services);
            return services.AddSignalR(static options =>
            {
                options.MaximumReceiveMessageSize = SignalRCarrier.MaximumBytes * FramingMultiplier;
                options.StreamBufferCapacity = 1;
                options.MaximumParallelInvocationsPerClient = InvocationCapacity;
                options.EnableDetailedErrors = false;
            }).AddJsonProtocol(static options => options.PayloadSerializerOptions.TypeInfoResolver = SignalRCarrierJsonContext.Default);
        }
    }
}
