// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

namespace ReactiveUI.Primitives.ObservableEvents;

/// <summary>The names the generator matches against consumer code and writes into generated source.</summary>
internal static class Constants
{
    /// <summary>The activation method name a consumer calls to request instance wrappers.</summary>
    internal const string EventMethodName = "Events";

    /// <summary>The class declaring the activation method, used to reject unrelated methods named Events.</summary>
    internal const string ActivationExtensionsDisplayName =
        "ReactiveUI.Primitives.ObservableEvents.ObservableGeneratorExtensions";

    /// <summary>The assembly attribute that requests static event wrappers, as written in source.</summary>
    internal const string StaticRequestAttributeName = "GenerateStaticEventObservables";

    /// <summary>The same attribute written with the suffix the language lets a user leave off.</summary>
    internal const string StaticRequestAttributeQualifiedName = "GenerateStaticEventObservablesAttribute";

    /// <summary>The hint name of the activation API emitted during post-initialization.</summary>
    internal const string ActivationHintName = "ObservableEvents.Activation.g.cs";

    /// <summary>The hint name of the file carrying every generated activation overload.</summary>
    internal const string ExtensionsHintName = "ObservableEvents.Extensions.g.cs";

    /// <summary>The namespace the activation API and its generated overloads live in.</summary>
    internal const string GeneratedNamespace = "ReactiveUI.Primitives.ObservableEvents";

    /// <summary>The partial class carrying the generated activation overloads.</summary>
    internal const string ActivationExtensionsClassName = "ObservableGeneratorExtensions";

    /// <summary>The partial class carrying generated static observable properties.</summary>
    internal const string StaticEventsClassName = "RxEvents";

    /// <summary>The marker every generated file opens with.</summary>
    internal const string GeneratedFileHeader = "// <auto-generated />\n";

    /// <summary>The directive that puts a generated file in a nullable-aware context.</summary>
    /// <remarks>
    /// Emitted only where the consumer's language version allows it, and always together with the annotations on
    /// the generated handler signatures: the directive is what makes those annotations mean anything, and the
    /// annotations are what make the handlers match the delegates they are assigned to.
    /// </remarks>
    internal const string NullableEnableDirective = "#nullable enable\n";

    /// <summary>The lean signal factory host, whose presence selects the lean provider.</summary>
    internal const string LeanSignalMetadataName = "ReactiveUI.Primitives.Signals.Signal";

    /// <summary>The shared disposable scope, required by both Primitives providers.</summary>
    internal const string ScopeMetadataName = "ReactiveUI.Primitives.Disposables.Scope";

    /// <summary>The lean void payload type, required by the lean provider.</summary>
    internal const string RxVoidMetadataName = "ReactiveUI.Primitives.RxVoid";

    /// <summary>The reactive-flavoured signal factory host.</summary>
    internal const string ReactiveSignalMetadataName = "ReactiveUI.Primitives.Reactive.Signals.Signal";

    /// <summary>The System.Reactive void payload type.</summary>
    internal const string ReactiveUnitMetadataName = "System.Reactive.Unit";

    /// <summary>The System.Reactive observable factory host.</summary>
    internal const string ReactiveObservableMetadataName = "System.Reactive.Linq.Observable";

    /// <summary>The System.Reactive disposable factory host.</summary>
    internal const string ReactiveDisposableMetadataName = "System.Reactive.Disposables.Disposable";

    /// <summary>The task type an event delegate may return.</summary>
    internal const string TaskMetadataName = "System.Threading.Tasks.Task";

    /// <summary>The value task type an event delegate may return.</summary>
    internal const string ValueTaskMetadataName = "System.Threading.Tasks.ValueTask";

    /// <summary>The lean observable factory written into generated source.</summary>
    internal const string LeanSignalCreate = "global::ReactiveUI.Primitives.Signals.Signal.Create";

    /// <summary>The reactive-flavoured observable factory written into generated source.</summary>
    internal const string ReactiveSignalCreate = "global::ReactiveUI.Primitives.Reactive.Signals.Signal.Create";

    /// <summary>The System.Reactive observable factory written into generated source.</summary>
    internal const string ObservableCreate = "global::System.Reactive.Linq.Observable.Create";

    /// <summary>The Primitives disposable factory written into generated source.</summary>
    internal const string ScopeCreate = "global::ReactiveUI.Primitives.Disposables.Scope.Create";

    /// <summary>The System.Reactive disposable factory written into generated source.</summary>
    internal const string DisposableCreate = "global::System.Reactive.Disposables.Disposable.Create";

    /// <summary>The lean void payload type written into generated source.</summary>
    internal const string RxVoidType = "global::ReactiveUI.Primitives.RxVoid";

    /// <summary>The System.Reactive void payload type written into generated source.</summary>
    internal const string ReactiveUnitType = "global::System.Reactive.Unit";

    /// <summary>The singleton member of whichever void payload type the provider selects.</summary>
    internal const string DefaultMember = ".Default";

    /// <summary>The completed task returned by a task-returning generated handler.</summary>
    internal const string CompletedTask = "global::System.Threading.Tasks.Task.CompletedTask";

    /// <summary>The value returned by a value-task-returning generated handler.</summary>
    internal const string DefaultValueTask = "default";
}
