// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ReactiveUI.Primitives.ObservableEvents;

/// <summary>Generates observable wrappers for event-bearing types requested by consumer source.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class EventGenerator : IIncrementalGenerator
{
    /// <summary>The activation method name.</summary>
    private const string EventMethodName = "Events";

    /// <summary>The indentation used for members nested one level.</summary>
    private const int MemberIndent = 4;

    /// <summary>The indentation used for members nested two levels.</summary>
    private const int NestedMemberIndent = 8;

    /// <summary>The offset basis for deterministic FNV-1a generated-name hashes.</summary>
    private const ulong HashOffsetBasis = 14_695_981_039_346_656_037;

    /// <summary>The prime for deterministic FNV-1a generated-name hashes.</summary>
    private const ulong HashPrime = 1_099_511_628_211;

    /// <summary>Source injected before normal incremental generation begins.</summary>
    private const string SupportSource = """
        // <auto-generated />
        #nullable enable
        namespace ReactiveUI.Primitives.ObservableEvents
        {
            /// <summary>Requests observable wrappers for public static events on a type.</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
            internal sealed class GenerateStaticEventObservablesAttribute : global::System.Attribute
            {
                /// <summary>Initializes the request.</summary>
                /// <param name="type">The static event host.</param>
                public GenerateStaticEventObservablesAttribute(global::System.Type type) => Type = type;

                /// <summary>Gets the requested static event host.</summary>
                public global::System.Type Type { get; }
            }

            /// <summary>Contains activation extensions used by the observable-event generator.</summary>
            internal static partial class ObservableGeneratorExtensions
            {
                /// <summary>Requests observable wrappers for the receiver's public events.</summary>
                /// <typeparam name="T">The event host type.</typeparam>
                /// <param name="eventHost">The event host.</param>
                /// <returns>A placeholder replaced by a generated, strongly typed overload.</returns>
                public static NullEvents Events<T>(this T eventHost) => default;
            }

            /// <summary>Placeholder returned until a strongly typed event wrapper is generated.</summary>
            internal readonly struct NullEvents
            {
            }
        }
        """;

    /// <summary>Reports that no supported observable factory is visible.</summary>
    private static readonly DiagnosticDescriptor MissingProvider = new(
        "RXOE001",
        "Observable provider not found",
        "Observable events for '{0}' require ReactiveUI.Primitives, ReactiveUI.Primitives.Reactive, or System.Reactive",
        "ReactiveUI.Primitives.ObservableEvents",
        DiagnosticSeverity.Warning,
        true);

    /// <summary>Reports that a requested target has no supported events.</summary>
    private static readonly DiagnosticDescriptor NoEvents = new(
        "RXOE002",
        "No supported events found",
        "No supported public {0} events were found on '{1}'",
        "ReactiveUI.Primitives.ObservableEvents",
        DiagnosticSeverity.Warning,
        true);

    /// <summary>Reports an event signature that cannot be represented safely.</summary>
    private static readonly DiagnosticDescriptor UnsupportedEvent = new(
        "RXOE003",
        "Event signature is not supported",
        "Event '{0}' cannot be exposed as an observable: {1}",
        "ReactiveUI.Primitives.ObservableEvents",
        DiagnosticSeverity.Warning,
        true);

    /// <summary>The observable implementation selected from consumer references.</summary>
    private enum Provider
    {
        /// <summary>ReactiveUI.Primitives lean implementation.</summary>
        Lean,

        /// <summary>ReactiveUI.Primitives.Reactive implementation.</summary>
        Reactive,

        /// <summary>Standalone System.Reactive implementation.</summary>
        SystemReactive,
    }

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource("ObservableEvents.Activation.g.cs", SourceText.From(SupportSource, Encoding.UTF8)));

        var requests = context.SyntaxProvider.CreateSyntaxProvider(
                IsEventsInvocation,
                GetInstanceRequest)
            .Collect();

        context.RegisterSourceOutput(
            requests.Combine(context.CompilationProvider),
            static (output, value) => Generate(output, value.Right, value.Left));
    }

    /// <summary>Determines whether syntax can represent an observable-events activation call.</summary>
    /// <param name="node">The syntax node being considered.</param>
    /// <param name="cancellationToken">A token that cancels candidate inspection.</param>
    /// <returns><see langword="true"/> when the node is a parameterless Events invocation.</returns>
    private static bool IsEventsInvocation(SyntaxNode node, CancellationToken cancellationToken)
    {
        _ = cancellationToken;
        return node is InvocationExpressionSyntax invocation
            && invocation.ArgumentList.Arguments.Count == 0
            && invocation.Expression is MemberAccessExpressionSyntax memberAccess
            && memberAccess.Name.Identifier.ValueText == EventMethodName;
    }

    /// <summary>Resolves a semantic instance-generation request from a candidate invocation.</summary>
    /// <param name="context">The semantic syntax-provider context.</param>
    /// <param name="cancellationToken">A token that cancels semantic inspection.</param>
    /// <returns>The resolved request, or <see langword="null"/> for an unrelated invocation.</returns>
    private static InstanceRequest? GetInstanceRequest(
        GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var method = context.SemanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol as IMethodSymbol;
        if (method?.ContainingType.ToDisplayString()
            != "ReactiveUI.Primitives.ObservableEvents.ObservableGeneratorExtensions")
        {
            return null;
        }

        var memberAccess = (MemberAccessExpressionSyntax)invocation.Expression;
        var receiverType = context.SemanticModel.GetTypeInfo(memberAccess.Expression, cancellationToken).Type as INamedTypeSymbol;
        return receiverType is null
            ? null
            : new InstanceRequest(receiverType.OriginalDefinition, invocation.GetLocation());
    }

    /// <summary>Generates all requested instance and static event adapters.</summary>
    /// <param name="context">The source-production context.</param>
    /// <param name="compilation">The consumer compilation.</param>
    /// <param name="candidateRequests">The collected instance requests.</param>
    private static void Generate(
        in SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<InstanceRequest?> candidateRequests)
    {
        var provider = GetProvider(compilation);
        var requests = DeduplicateRequests(candidateRequests);
        var staticRequests = GetStaticRequests(compilation);
        if (requests.Count == 0 && staticRequests.Count == 0)
        {
            return;
        }

        if (provider is null)
        {
            ReportMissingProviders(context, requests, staticRequests);
            return;
        }

        var resolvedProvider = provider.Value;

        var extensionMethods = new StringBuilder();
        foreach (var request in requests)
        {
            GenerateInstanceTarget(context, compilation, resolvedProvider, request, extensionMethods);
        }

        if (extensionMethods.Length > 0)
        {
            context.AddSource(
                "ObservableEvents.Extensions.g.cs",
                SourceText.From(WrapExtensions(extensionMethods), Encoding.UTF8));
        }

        GenerateStaticTargets(context, compilation, resolvedProvider, staticRequests);
    }

    /// <summary>Selects the best observable provider visible to the consumer compilation.</summary>
    /// <param name="compilation">The consumer compilation.</param>
    /// <returns>The selected provider, or <see langword="null"/> when none is available.</returns>
    private static Provider? GetProvider(Compilation compilation)
    {
        if (compilation.GetTypeByMetadataName("ReactiveUI.Primitives.Signals.Signal") is not null
            && compilation.GetTypeByMetadataName("ReactiveUI.Primitives.Disposables.Scope") is not null
            && compilation.GetTypeByMetadataName("ReactiveUI.Primitives.RxVoid") is not null)
        {
            return Provider.Lean;
        }

        if (compilation.GetTypeByMetadataName("ReactiveUI.Primitives.Reactive.Signals.Signal") is not null
            && compilation.GetTypeByMetadataName("ReactiveUI.Primitives.Disposables.Scope") is not null
            && compilation.GetTypeByMetadataName("System.Reactive.Unit") is not null)
        {
            return Provider.Reactive;
        }

        return compilation.GetTypeByMetadataName("System.Reactive.Linq.Observable") is not null
               && compilation.GetTypeByMetadataName("System.Reactive.Disposables.Disposable") is not null
               && compilation.GetTypeByMetadataName("System.Reactive.Unit") is not null
            ? Provider.SystemReactive
            : null;
    }

    /// <summary>Deduplicates repeated activation calls for the same host type.</summary>
    /// <param name="requests">The candidate activation requests.</param>
    /// <returns>The distinct requests in source order.</returns>
    private static List<InstanceRequest> DeduplicateRequests(ImmutableArray<InstanceRequest?> requests)
    {
        var result = new List<InstanceRequest>();
        var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var candidate in requests)
        {
            if (candidate is not null && seen.Add(candidate.Type))
            {
                result.Add(candidate);
            }
        }

        return result;
    }

    /// <summary>Finds distinct assembly-level static generation requests.</summary>
    /// <param name="compilation">The consumer compilation.</param>
    /// <returns>The distinct static requests.</returns>
    private static List<StaticRequest> GetStaticRequests(Compilation compilation)
    {
        var result = new List<StaticRequest>();
        var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var attribute in compilation.Assembly.GetAttributes())
        {
            if (attribute.AttributeClass!.ToDisplayString()
                    != "ReactiveUI.Primitives.ObservableEvents.GenerateStaticEventObservablesAttribute"
                || attribute.ConstructorArguments.Length != 1
                || attribute.ConstructorArguments[0].Value is not INamedTypeSymbol target)
            {
                continue;
            }

            target = target.OriginalDefinition;
            if (seen.Add(target))
            {
                var location = attribute.ApplicationSyntaxReference!.GetSyntax().GetLocation();
                result.Add(new(target, location));
            }
        }

        return result;
    }

    /// <summary>Reports a missing provider for every requested host.</summary>
    /// <param name="context">The source-production context.</param>
    /// <param name="requests">The instance requests to diagnose.</param>
    /// <param name="staticRequests">The static requests to diagnose.</param>
    private static void ReportMissingProviders(
        in SourceProductionContext context,
        IReadOnlyList<InstanceRequest> requests,
        IReadOnlyList<StaticRequest> staticRequests)
    {
        foreach (var request in requests)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                MissingProvider,
                request.Location,
                request.Type.ToDisplayString()));
        }

        foreach (var request in staticRequests)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                MissingProvider,
                request.Location,
                request.Type.ToDisplayString()));
        }
    }

    /// <summary>Generates one strongly typed instance wrapper and activation overload.</summary>
    /// <param name="context">The source-production context.</param>
    /// <param name="compilation">The consumer compilation.</param>
    /// <param name="provider">The selected observable provider.</param>
    /// <param name="request">The instance-generation request.</param>
    /// <param name="extensionMethods">The shared extension-method source builder.</param>
    private static void GenerateInstanceTarget(
        in SourceProductionContext context,
        Compilation compilation,
        Provider provider,
        InstanceRequest request,
        StringBuilder extensionMethods)
    {
        var events = GetEvents(context, compilation, request.Type, false, request.Location);
        if (events.Count == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                NoEvents,
                request.Location,
                "instance",
                request.Type.ToDisplayString()));
            return;
        }

        var wrapperName = GetWrapperName(request.Type);
        var source = GenerateInstanceWrapper(provider, request.Type, events, wrapperName);
        context.AddSource(GetHintName(request.Type, "Instance"), SourceText.From(source, Encoding.UTF8));
        AppendExtensionMethod(extensionMethods, request.Type, wrapperName);
    }

    /// <summary>Generates all assembly-requested static event properties.</summary>
    /// <param name="context">The source-production context.</param>
    /// <param name="compilation">The consumer compilation.</param>
    /// <param name="provider">The selected observable provider.</param>
    /// <param name="requests">The static-generation requests.</param>
    private static void GenerateStaticTargets(
        in SourceProductionContext context,
        Compilation compilation,
        Provider provider,
        IReadOnlyList<StaticRequest> requests)
    {
        var byNamespace = new Dictionary<string, StringBuilder>(StringComparer.Ordinal);
        foreach (var request in requests)
        {
            if (request.Type.IsGenericType)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    UnsupportedEvent,
                    request.Location,
                    request.Type.ToDisplayString(),
                    "generic static event hosts are not supported"));
                continue;
            }

            var events = GetEvents(context, compilation, request.Type, true, request.Location);
            if (events.Count == 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    NoEvents,
                    request.Location,
                    "static",
                    request.Type.ToDisplayString()));
                continue;
            }

            var namespaceName = request.Type.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : request.Type.ContainingNamespace.ToDisplayString();
            if (!byNamespace.TryGetValue(namespaceName, out var members))
            {
                members = new();
                byNamespace.Add(namespaceName, members);
            }

            foreach (var eventSymbol in events)
            {
                AppendEventProperty(
                    members,
                    provider,
                    eventSymbol,
                    GetStaticPropertyName(request.Type, eventSymbol.Name),
                    null,
                    true,
                    null);
            }
        }

        foreach (var pair in byNamespace)
        {
            context.AddSource(
                $"ObservableEvents.{GetUniqueNameComponent(pair.Key)}.Static.g.cs",
                SourceText.From(WrapStaticEvents(pair.Key, pair.Value), Encoding.UTF8));
        }
    }

    /// <summary>Collects supported public events from a target and its base types.</summary>
    /// <param name="context">The source-production context.</param>
    /// <param name="compilation">The consumer compilation.</param>
    /// <param name="target">The event host type.</param>
    /// <param name="isStatic">Whether static events are requested.</param>
    /// <param name="requestLocation">The request location used for diagnostics.</param>
    /// <returns>The supported events visible on the target.</returns>
    private static List<IEventSymbol> GetEvents(
        in SourceProductionContext context,
        Compilation compilation,
        INamedTypeSymbol target,
        bool isStatic,
        Location requestLocation)
    {
        var result = new List<IEventSymbol>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        for (INamedTypeSymbol? current = target; current is not null; current = current.BaseType)
        {
            foreach (var member in current.GetMembers())
            {
                if (member is not IEventSymbol eventSymbol)
                {
                    continue;
                }

                if (eventSymbol.IsStatic != isStatic
                    || eventSymbol.DeclaredAccessibility != Accessibility.Public
                    || !seen.Add(eventSymbol.Name))
                {
                    continue;
                }

                var reason = GetUnsupportedReason(compilation, eventSymbol);
                if (reason is null)
                {
                    result.Add(eventSymbol);
                }
                else
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        UnsupportedEvent,
                        requestLocation,
                        eventSymbol.ToDisplayString(),
                        reason));
                }
            }
        }

        return result;
    }

    /// <summary>Returns the reason an event cannot be generated, or null when it is supported.</summary>
    /// <param name="compilation">The consumer compilation.</param>
    /// <param name="eventSymbol">The event to validate.</param>
    /// <returns>The unsupported reason, or <see langword="null"/> when the event is supported.</returns>
    private static string? GetUnsupportedReason(Compilation compilation, IEventSymbol eventSymbol)
    {
        if (eventSymbol.Type is not INamedTypeSymbol { DelegateInvokeMethod: { } invokeMethod })
        {
            return "the event type is not a delegate";
        }

        foreach (var parameter in invokeMethod.Parameters)
        {
            if (parameter.RefKind != RefKind.None)
            {
                return "by-reference delegate parameters are not supported";
            }

            if (parameter.Type.TypeKind is TypeKind.Pointer or TypeKind.FunctionPointer || parameter.Type.IsRefLikeType)
            {
                return "pointer, function-pointer, and ref-like payloads are not supported";
            }
        }

        if (invokeMethod.ReturnsVoid)
        {
            return null;
        }

        var task = compilation.GetTypeByMetadataName("System.Threading.Tasks.Task");
        var valueTask = compilation.GetTypeByMetadataName("System.Threading.Tasks.ValueTask");
        return SymbolEqualityComparer.Default.Equals(invokeMethod.ReturnType, task)
               || SymbolEqualityComparer.Default.Equals(invokeMethod.ReturnType, valueTask)
            ? null
            : "the delegate must return void, Task, or ValueTask";
    }

    /// <summary>Builds source for one instance event wrapper.</summary>
    /// <param name="provider">The selected observable provider.</param>
    /// <param name="type">The event host type.</param>
    /// <param name="events">The supported events to expose.</param>
    /// <param name="wrapperName">The generated wrapper class name.</param>
    /// <returns>The generated instance-wrapper source.</returns>
    private static string GenerateInstanceWrapper(
        Provider provider,
        INamedTypeSymbol type,
        IReadOnlyList<IEventSymbol> events,
        string wrapperName)
    {
        var typeParameterNames = GetTypeParameterNames(type);
        var members = new StringBuilder();
        var typeReference = Display(type, typeParameterNames);
        _ = members.Append("    private readonly ").Append(typeReference).AppendLine(" _host;")
            .AppendLine()
            .Append("    internal ").Append(wrapperName).Append('(')
            .Append(typeReference).AppendLine(" host) => _host = host;")
            .AppendLine();
        foreach (var eventSymbol in events)
        {
            AppendEventProperty(
                members,
                provider,
                eventSymbol,
                eventSymbol.Name,
                "_host",
                false,
                typeParameterNames);
        }

        var declaration = new StringBuilder()
            .Append("internal sealed class ").Append(wrapperName)
            .Append(GetTypeParameterList(type, typeParameterNames)).AppendLine()
            .Append(GetConstraints(type, typeParameterNames))
            .AppendLine("{")
            .Append(members)
            .AppendLine("}")
            .ToString();
        return WrapNamespace(type.ContainingNamespace, declaration);
    }

    /// <summary>Appends the strongly typed Events extension for a host.</summary>
    /// <param name="builder">The shared extension-method source builder.</param>
    /// <param name="type">The event host type.</param>
    /// <param name="wrapperName">The generated wrapper class name.</param>
    private static void AppendExtensionMethod(StringBuilder builder, INamedTypeSymbol type, string wrapperName)
    {
        var typeParameterNames = GetTypeParameterNames(type);
        var typeParameters = GetTypeParameterList(type, typeParameterNames);
        var wrapperReference = GetNamespacePrefix(type.ContainingNamespace) + wrapperName + typeParameters;
        _ = builder.Append("        /// <summary>Gets observable wrappers for public events on <see cref=\"")
            .Append(Display(type, typeParameterNames)).AppendLine("\"/>.</summary>")
            .Append("        public static ").Append(wrapperReference).Append(" Events")
            .Append(typeParameters).Append("(this ").Append(Display(type, typeParameterNames)).AppendLine(" eventHost)")
            .Append(Indent(GetConstraints(type, typeParameterNames), NestedMemberIndent))
            .Append("            => new ").Append(wrapperReference).AppendLine("(eventHost);")
            .AppendLine();
    }

    /// <summary>Appends an observable property for an event.</summary>
    /// <param name="builder">The destination source builder.</param>
    /// <param name="provider">The selected observable provider.</param>
    /// <param name="eventSymbol">The event to expose.</param>
    /// <param name="propertyName">The generated property name.</param>
    /// <param name="hostField">The instance-host expression, or <see langword="null"/> for static events.</param>
    /// <param name="isStatic">Whether the generated property and event subscription are static.</param>
    /// <param name="typeParameterNames">The generated type-parameter names for an instance wrapper.</param>
    private static void AppendEventProperty(
        StringBuilder builder,
        Provider provider,
        IEventSymbol eventSymbol,
        string propertyName,
        string? hostField,
        bool isStatic,
        IReadOnlyDictionary<ITypeParameterSymbol, string>? typeParameterNames)
    {
        var invokeMethod = ((INamedTypeSymbol)eventSymbol.Type).DelegateInvokeMethod!;
        var payloadType = GetPayloadType(provider, invokeMethod, typeParameterNames);
        var eventTarget = isStatic
            ? Display(eventSymbol.ContainingType)
            : $"(({Display(eventSymbol.ContainingType, typeParameterNames)}){hostField})";
        var handlerParameters = JoinParameters(invokeMethod.Parameters, true, typeParameterNames);
        var payloadValue = GetPayloadValue(provider, invokeMethod);
        var returnPrefix = invokeMethod.ReturnsVoid ? string.Empty : "return ";
        var returnValue = GetReturnValue(invokeMethod);

        _ = builder.Append("    /// <summary>Gets an observable that signals when the ")
            .Append(EscapeXml(eventSymbol.Name)).AppendLine(" event is raised.</summary>")
            .Append("    public ").Append(isStatic ? "static " : string.Empty)
            .Append("global::System.IObservable<").Append(payloadType).Append("> ")
            .Append(EscapeIdentifier(propertyName)).Append(" => ").Append(GetFactory(provider))
            .Append('<').Append(payloadType).AppendLine(">(observer =>")
            .AppendLine("    {")
            .Append("        ").Append(Display(invokeMethod.ReturnType, typeParameterNames)).Append(" Handler(")
            .Append(handlerParameters).AppendLine(")")
            .AppendLine("        {")
            .Append("            observer.OnNext(").Append(payloadValue).AppendLine(");");
        if (!invokeMethod.ReturnsVoid)
        {
            _ = builder.Append("            ").Append(returnPrefix).Append(returnValue).AppendLine(";");
        }

        _ = builder.AppendLine("        }")
            .Append("        ").Append(eventTarget).Append('.').Append(EscapeIdentifier(eventSymbol.Name))
            .AppendLine(" += Handler;")
            .Append("        return ").Append(GetDisposableFactory(provider)).Append("(() => ")
            .Append(eventTarget).Append('.').Append(EscapeIdentifier(eventSymbol.Name)).AppendLine(" -= Handler);")
            .AppendLine("    });")
            .AppendLine();
    }

    /// <summary>Gets the observable payload type for a delegate.</summary>
    /// <param name="provider">The selected observable provider.</param>
    /// <param name="invokeMethod">The delegate invocation method.</param>
    /// <param name="typeParameterNames">The generated type-parameter names.</param>
    /// <returns>The fully qualified payload type source.</returns>
    private static string GetPayloadType(
        Provider provider,
        IMethodSymbol invokeMethod,
        IReadOnlyDictionary<ITypeParameterSymbol, string>? typeParameterNames)
    {
        if (invokeMethod.Parameters.IsEmpty)
        {
            return provider == Provider.Lean
                ? "global::ReactiveUI.Primitives.RxVoid"
                : "global::System.Reactive.Unit";
        }

        if (invokeMethod.Parameters.Length == 1)
        {
            return Display(invokeMethod.Parameters[0].Type, typeParameterNames);
        }

        return invokeMethod.Parameters.Length == 2
               && invokeMethod.Parameters[0].Type.SpecialType == SpecialType.System_Object
            ? Display(invokeMethod.Parameters[1].Type, typeParameterNames)
            : $"({JoinParameters(invokeMethod.Parameters, true, typeParameterNames)})";
    }

    /// <summary>Gets the observer value expression for a delegate invocation.</summary>
    /// <param name="provider">The selected observable provider.</param>
    /// <param name="invokeMethod">The delegate invocation method.</param>
    /// <returns>The payload value expression.</returns>
    private static string GetPayloadValue(Provider provider, IMethodSymbol invokeMethod)
    {
        if (invokeMethod.Parameters.IsEmpty)
        {
            return provider == Provider.Lean
                ? "global::ReactiveUI.Primitives.RxVoid.Default"
                : "global::System.Reactive.Unit.Default";
        }

        if (invokeMethod.Parameters.Length == 1)
        {
            return EscapeIdentifier(invokeMethod.Parameters[0].Name);
        }

        return invokeMethod.Parameters.Length == 2
               && invokeMethod.Parameters[0].Type.SpecialType == SpecialType.System_Object
            ? EscapeIdentifier(invokeMethod.Parameters[1].Name)
            : $"({JoinParameters(invokeMethod.Parameters, false, null)})";
    }

    /// <summary>Gets the return expression for Task and ValueTask event handlers.</summary>
    /// <param name="invokeMethod">The delegate invocation method.</param>
    /// <returns>The completed return expression.</returns>
    private static string GetReturnValue(IMethodSymbol invokeMethod) =>
        invokeMethod.ReturnType.ToDisplayString() == "System.Threading.Tasks.Task"
            ? "global::System.Threading.Tasks.Task.CompletedTask"
            : "default";

    /// <summary>Formats one delegate handler parameter.</summary>
    /// <param name="parameter">The delegate parameter.</param>
    /// <param name="typeParameterNames">The generated type-parameter names.</param>
    /// <returns>The parameter declaration source.</returns>
    private static string FormatParameter(
        IParameterSymbol parameter,
        IReadOnlyDictionary<ITypeParameterSymbol, string>? typeParameterNames) =>
        $"{Display(parameter.Type, typeParameterNames)} {EscapeIdentifier(parameter.Name)}";

    /// <summary>Joins delegate parameter declarations or value expressions.</summary>
    /// <param name="parameters">The delegate parameters.</param>
    /// <param name="includeTypes">Whether each item includes its fully qualified type.</param>
    /// <param name="typeParameterNames">The generated type-parameter names.</param>
    /// <returns>The comma-separated parameter source.</returns>
    private static string JoinParameters(
        ImmutableArray<IParameterSymbol> parameters,
        bool includeTypes,
        IReadOnlyDictionary<ITypeParameterSymbol, string>? typeParameterNames)
    {
        var builder = new StringBuilder();
        for (var index = 0; index < parameters.Length; index++)
        {
            if (index > 0)
            {
                _ = builder.Append(", ");
            }

            _ = builder.Append(includeTypes
                ? FormatParameter(parameters[index], typeParameterNames)
                : EscapeIdentifier(parameters[index].Name));
        }

        return builder.ToString();
    }

    /// <summary>Gets the selected observable creation method.</summary>
    /// <param name="provider">The selected observable provider.</param>
    /// <returns>The fully qualified observable factory method.</returns>
    private static string GetFactory(Provider provider) => provider switch
    {
        Provider.Lean => "global::ReactiveUI.Primitives.Signals.Signal.Create",
        Provider.Reactive => "global::ReactiveUI.Primitives.Reactive.Signals.Signal.Create",
        _ => "global::System.Reactive.Linq.Observable.Create",
    };

    /// <summary>Gets the selected disposable creation method.</summary>
    /// <param name="provider">The selected observable provider.</param>
    /// <returns>The fully qualified disposable factory method.</returns>
    private static string GetDisposableFactory(Provider provider) =>
        provider == Provider.SystemReactive
            ? "global::System.Reactive.Disposables.Disposable.Create"
            : "global::ReactiveUI.Primitives.Disposables.Scope.Create";

    /// <summary>Wraps generated instance activation overloads in their shared extension class.</summary>
    /// <param name="methods">The generated activation overloads.</param>
    /// <returns>The complete extension-class source.</returns>
    private static string WrapExtensions(StringBuilder methods) => $$"""
        // <auto-generated />
        #nullable enable
        namespace ReactiveUI.Primitives.ObservableEvents
        {
            internal static partial class ObservableGeneratorExtensions
            {
        {{methods}}    }
        }
        """;

    /// <summary>Wraps generated static properties in the requested namespace.</summary>
    /// <param name="namespaceName">The target namespace, or an empty string for the global namespace.</param>
    /// <param name="members">The generated static observable properties.</param>
    /// <returns>The complete static-wrapper source.</returns>
    private static string WrapStaticEvents(string namespaceName, StringBuilder members)
    {
        var declaration = new StringBuilder()
            .AppendLine("internal static partial class RxEvents")
            .AppendLine("{")
            .Append(members)
            .AppendLine("}")
            .ToString();
        return namespaceName.Length == 0
            ? $"// <auto-generated />\n#nullable enable\n{declaration}"
            : $"// <auto-generated />\n#nullable enable\nnamespace {namespaceName}\n{{\n"
              + $"{Indent(declaration, MemberIndent)}}}\n";
    }

    /// <summary>Wraps a declaration in a namespace, accounting for the global namespace.</summary>
    /// <param name="namespaceSymbol">The target namespace.</param>
    /// <param name="declaration">The declaration source to wrap.</param>
    /// <returns>The complete generated source.</returns>
    private static string WrapNamespace(INamespaceSymbol namespaceSymbol, string declaration) =>
        namespaceSymbol.IsGlobalNamespace
            ? $"// <auto-generated />\n#nullable enable\n{declaration}"
            : $"// <auto-generated />\n#nullable enable\nnamespace {namespaceSymbol.ToDisplayString()}\n{{\n"
              + $"{Indent(declaration, MemberIndent)}}}\n";

    /// <summary>Gets all containing and target type parameters as a declaration list.</summary>
    /// <param name="type">The target type.</param>
    /// <param name="typeParameterNames">The generated type-parameter names.</param>
    /// <returns>The type-parameter declaration list, or an empty string for a non-generic type.</returns>
    private static string GetTypeParameterList(
        INamedTypeSymbol type,
        Dictionary<ITypeParameterSymbol, string> typeParameterNames)
    {
        var parameters = GetAllTypeParameters(type);
        if (parameters.Count == 0)
        {
            return string.Empty;
        }

        var names = new string[parameters.Count];
        for (var index = 0; index < parameters.Count; index++)
        {
            names[index] = typeParameterNames[parameters[index]];
        }

        return $"<{string.Join(", ", names)}>";
    }

    /// <summary>Gets generic constraints for all containing and target type parameters.</summary>
    /// <param name="type">The target type.</param>
    /// <param name="typeParameterNames">The generated type-parameter names.</param>
    /// <returns>The generic constraint clauses.</returns>
    private static string GetConstraints(
        INamedTypeSymbol type,
        Dictionary<ITypeParameterSymbol, string> typeParameterNames)
    {
        var builder = new StringBuilder();
        foreach (var parameter in GetAllTypeParameters(type))
        {
            var constraints = new List<string>();
            if (parameter.HasUnmanagedTypeConstraint)
            {
                constraints.Add("unmanaged");
            }
            else if (parameter.HasValueTypeConstraint)
            {
                constraints.Add("struct");
            }
            else if (parameter.HasReferenceTypeConstraint)
            {
                constraints.Add(parameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated
                    ? "class?"
                    : "class");
            }
            else if (parameter.HasNotNullConstraint)
            {
                constraints.Add("notnull");
            }

            foreach (var constraintType in parameter.ConstraintTypes)
            {
                constraints.Add(Display(constraintType, typeParameterNames));
            }

            if (parameter.HasConstructorConstraint)
            {
                constraints.Add("new()");
            }

            if (constraints.Count > 0)
            {
                _ = builder.Append("    where ").Append(typeParameterNames[parameter]).Append(" : ")
                    .AppendLine(string.Join(", ", constraints));
            }
        }

        return builder.ToString();
    }

    /// <summary>Collects containing and target type parameters in declaration order.</summary>
    /// <param name="type">The target type.</param>
    /// <returns>The complete ordered type-parameter list.</returns>
    private static List<ITypeParameterSymbol> GetAllTypeParameters(INamedTypeSymbol type)
    {
        var types = new Stack<INamedTypeSymbol>();
        for (var current = type; current is not null; current = current.ContainingType)
        {
            types.Push(current);
        }

        var result = new List<ITypeParameterSymbol>();
        while (types.Count > 0)
        {
            result.AddRange(types.Pop().TypeParameters);
        }

        return result;
    }

    /// <summary>Creates unique generated identifiers for containing and target type parameters.</summary>
    /// <param name="type">The target type.</param>
    /// <returns>The symbol-to-generated-name mapping.</returns>
    private static Dictionary<ITypeParameterSymbol, string> GetTypeParameterNames(INamedTypeSymbol type)
    {
        var result = new Dictionary<ITypeParameterSymbol, string>(SymbolEqualityComparer.Default);
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var parameter in GetAllTypeParameters(type))
        {
            var baseName = parameter.Name;
            var name = baseName;
            var suffix = 1;
            while (!usedNames.Add(name))
            {
                suffix++;
                name = baseName + suffix.ToString(CultureInfo.InvariantCulture);
            }

            result.Add(parameter, EscapeIdentifier(name));
        }

        return result;
    }

    /// <summary>Gets a collision-free static observable property name.</summary>
    /// <param name="type">The static event host.</param>
    /// <param name="eventName">The event name.</param>
    /// <returns>The generated property name.</returns>
    private static string GetStaticPropertyName(INamedTypeSymbol type, string eventName)
    {
        var types = new Stack<INamedTypeSymbol>();
        for (var current = type; current is not null; current = current.ContainingType)
        {
            types.Push(current);
        }

        var builder = new StringBuilder("T");
        while (types.Count > 0)
        {
            var name = types.Pop().Name;
            _ = builder.Append(name.Length.ToString(CultureInfo.InvariantCulture)).Append(name);
        }

        return builder.Append(eventName.Length.ToString(CultureInfo.InvariantCulture)).Append(eventName).ToString();
    }

    /// <summary>Gets a collision-resistant wrapper class name.</summary>
    /// <param name="type">The target type.</param>
    /// <returns>The generated wrapper class name.</returns>
    private static string GetWrapperName(INamedTypeSymbol type) =>
        $"Rx{GetUniqueNameComponent(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))}Events";

    /// <summary>Gets a deterministic generated-source hint name.</summary>
    /// <param name="type">The target type.</param>
    /// <param name="suffix">The generated-source category suffix.</param>
    /// <returns>The deterministic hint name.</returns>
    private static string GetHintName(INamedTypeSymbol type, string suffix) =>
        $"ObservableEvents.{GetUniqueNameComponent(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))}.{suffix}.g.cs";

    /// <summary>Gets a fully qualified namespace prefix.</summary>
    /// <param name="namespaceSymbol">The namespace symbol.</param>
    /// <returns>The global namespace prefix.</returns>
    private static string GetNamespacePrefix(INamespaceSymbol namespaceSymbol) => namespaceSymbol.IsGlobalNamespace
        ? "global::"
        : $"global::{namespaceSymbol.ToDisplayString()}.";

    /// <summary>Formats a symbol as a fully qualified C# type.</summary>
    /// <param name="symbol">The type symbol.</param>
    /// <param name="typeParameterNames">The generated type-parameter names.</param>
    /// <returns>The fully qualified type source.</returns>
    private static string Display(
        ITypeSymbol symbol,
        IReadOnlyDictionary<ITypeParameterSymbol, string>? typeParameterNames = null)
    {
        if (typeParameterNames is null || typeParameterNames.Count == 0)
        {
            return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        var builder = new StringBuilder();
        foreach (var part in symbol.ToDisplayParts(SymbolDisplayFormat.FullyQualifiedFormat))
        {
            _ = builder.Append(
                part.Symbol is ITypeParameterSymbol parameter
                && typeParameterNames.TryGetValue(parameter, out var replacement)
                    ? replacement
                    : part.ToString());
        }

        return builder.ToString();
    }

    /// <summary>Escapes C# keyword identifiers.</summary>
    /// <param name="value">The identifier text.</param>
    /// <returns>The escaped identifier.</returns>
    private static string EscapeIdentifier(string value) => SyntaxFacts.GetKeywordKind(value) == SyntaxKind.None
        ? value
        : $"@{value}";

    /// <summary>Converts a symbol display into a safe class or hint-name component.</summary>
    /// <param name="value">The symbol display text.</param>
    /// <returns>The sanitized identifier component.</returns>
    private static string Sanitize(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            _ = builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return builder.ToString().Trim('_');
    }

    /// <summary>Creates a readable generated-name component with a stable collision-resistant suffix.</summary>
    /// <param name="value">The original symbol or namespace identity.</param>
    /// <returns>The unique generated-name component.</returns>
    private static string GetUniqueNameComponent(string value) =>
        $"{Sanitize(value)}_{GetStableHash(value)}";

    /// <summary>Computes a deterministic FNV-1a hash for generated names.</summary>
    /// <param name="value">The identity to hash.</param>
    /// <returns>The invariant uppercase hexadecimal hash.</returns>
    private static string GetStableHash(string value)
    {
        var hash = HashOffsetBasis;
        foreach (var character in value)
        {
            hash ^= character;
            hash *= HashPrime;
        }

        return hash.ToString("X16", CultureInfo.InvariantCulture);
    }

    /// <summary>Escapes text inserted into generated XML documentation.</summary>
    /// <param name="value">The documentation text.</param>
    /// <returns>The XML-escaped text.</returns>
    private static string EscapeXml(string value) => value.Replace("&", "&amp;").Replace("<", "&lt;")
        .Replace(">", "&gt;").Replace("\"", "&quot;").Replace("'", "&apos;");

    /// <summary>Indents every line in a generated source fragment.</summary>
    /// <param name="value">The source fragment.</param>
    /// <param name="spaces">The number of leading spaces.</param>
    /// <returns>The indented source fragment.</returns>
    private static string Indent(string value, int spaces)
    {
        if (value.Length == 0)
        {
            return value;
        }

        var indent = new string(' ', spaces);
        return $"{indent}{value.Replace("\n", $"\n{indent}").TrimEnd()}\n";
    }

    /// <summary>An instance wrapper request and its diagnostic location.</summary>
    /// <param name="type">The requested host type.</param>
    /// <param name="location">The request location.</param>
    private sealed class InstanceRequest(INamedTypeSymbol type, Location location)
    {
        /// <summary>Gets the requested host type.</summary>
        public INamedTypeSymbol Type { get; } = type;

        /// <summary>Gets the activation call location.</summary>
        public Location Location { get; } = location;
    }

    /// <summary>A static wrapper request and its diagnostic location.</summary>
    /// <param name="type">The requested host type.</param>
    /// <param name="location">The request location.</param>
    private sealed class StaticRequest(INamedTypeSymbol type, Location location)
    {
        /// <summary>Gets the requested static host type.</summary>
        public INamedTypeSymbol Type { get; } = type;

        /// <summary>Gets the assembly attribute location.</summary>
        public Location Location { get; } = location;
    }
}
