<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(BlazorTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ReactiveUI.Primitives.Blazor.Reactive\ReactiveUI.Primitives.Blazor.Reactive.csproj"/>
  </ItemGroup>

</Project>
