<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>$(NetTargetFrameworks)</TargetFrameworks>
    <RootNamespace>ReactiveUI.Primitives.OccasionallyConnected.Collaboration.Server</RootNamespace>
    <AssemblyName>ReactiveUI.Primitives.OccasionallyConnected.Collaboration.Server</AssemblyName>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <EnableSystemTextJsonSourceGenerator>true</EnableSystemTextJsonSourceGenerator>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ReactiveUI.Primitives.OccasionallyConnected.Core\ReactiveUI.Primitives.OccasionallyConnected.Core.csproj" />
    <ProjectReference Include="..\..\ReactiveUI.Primitives.OccasionallyConnected.Server\ReactiveUI.Primitives.OccasionallyConnected.Server.csproj" />
    <ProjectReference Include="..\..\ReactiveUI.Primitives.OccasionallyConnected.Transport.Http\ReactiveUI.Primitives.OccasionallyConnected.Transport.Http.csproj" />
  </ItemGroup>

</Project>
