// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Runtime.CompilerServices;

namespace ReactiveUI.Primitives.Async;

/// <summary>
/// Provides factory methods for creating observable sequences that are generated by invoking a specified function each
/// time a new observer subscribes.
/// </summary>
/// <remarks>The methods in this class enable deferred creation of asynchronous observable sequences. Each
/// subscription triggers a new invocation of the provided factory function, ensuring that each observer receives a
/// fresh sequence. This is useful for scenarios where the observable's behavior or state should be determined at the
/// time of subscription rather than at the time of declaration.</remarks>
public static partial class SignalAsync
{
    /// <summary>Creates a new observable sequence for each subscription by invoking the specified asynchronous factory function.</summary>
    /// <typeparam name="T">The type of the elements produced by the observable sequence.</typeparam>
    /// <param name="factory">A function that receives a cancellation token and returns a task that produces an observable sequence to
    /// subscribe to.</param>
    /// <returns>An observable sequence that, upon each subscription, invokes the factory function to obtain the actual
    /// observable sequence to subscribe to.</returns>
    /// <remarks>Use this method to defer the creation of the observable sequence until an observer
    /// subscribes. This is useful when the observable sequence depends on per-subscription state or resources, or when
    /// you want to ensure a fresh sequence for each subscriber.</remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static IObservableAsync<T> Defer<T>(Func<CancellationToken, ValueTask<IObservableAsync<T>>> factory) =>
        new DeferAsyncSignalAsync<T>(factory);

    /// <summary>
    /// Returns an observable sequence that is created by invoking the specified factory function each time a new
    /// observer subscribes.
    /// </summary>
    /// <typeparam name="T">The type of the elements produced by the observable sequence.</typeparam>
    /// <param name="factory">A function that returns a new instance of an observable sequence to be subscribed to for each observer.</param>
    /// <returns>An observable sequence whose observers trigger the invocation of the factory function upon subscription.</returns>
    /// <remarks>Use this method to defer the creation of the observable sequence until an observer
    /// subscribes, ensuring that each subscription receives a fresh instance. This is useful when the observable
    /// sequence has side effects or depends on external state at the time of subscription.</remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static IObservableAsync<T> Defer<T>(Func<IObservableAsync<T>> factory) =>
        new DeferSyncSignalAsync<T>(factory);

    /// <summary>Dedicated observable for <see cref="Defer{T}(Func{IObservableAsync{T}})"/>.
    /// Holds the factory delegate directly — no closure-capturing lambda, no
    /// <see cref="Create{T}"/>-wrapper indirection. Per-subscribe path invokes the factory,
    /// wraps the downstream observer once for contract compliance, and subscribes to the
    /// freshly-produced inner observable.</summary>
    /// <typeparam name="T">The element type.</typeparam>
    /// <param name="factory">The deferred factory invoked once per subscribe.</param>
    internal sealed class DeferSyncSignalAsync<T>(Func<IObservableAsync<T>> factory) : IObservableAsync<T>
    {
        /// <inheritdoc/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        ValueTask<IAsyncDisposable> IObservableAsync<T>.SubscribeAsync(
            IObserverAsync<T> observer,
            CancellationToken cancellationToken) =>
            factory().SubscribeAsync(observer.Wrap(), cancellationToken);
    }

    /// <summary>Dedicated observable for the <see cref="ValueTask"/>-returning
    /// <see cref="Defer{T}(Func{CancellationToken, ValueTask{IObservableAsync{T}}})"/>.
    /// Same allocation profile as <see cref="DeferSyncSignalAsync{T}"/> with one extra
    /// state-machine box per call to host the factory's <c>await</c>.</summary>
    /// <typeparam name="T">The element type.</typeparam>
    /// <param name="factory">The deferred factory invoked once per subscribe.</param>
    internal sealed class DeferAsyncSignalAsync<T>(Func<CancellationToken, ValueTask<IObservableAsync<T>>> factory) : IObservableAsync<T>
    {
        /// <inheritdoc/>
        async ValueTask<IAsyncDisposable> IObservableAsync<T>.SubscribeAsync(
            IObserverAsync<T> observer,
            CancellationToken cancellationToken)
        {
            var signal = await factory(cancellationToken).ConfigureAwait(false);
            return await signal.SubscribeAsync(observer.Wrap(), cancellationToken).ConfigureAwait(false);
        }
    }
}
