// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Runtime.CompilerServices;

namespace ReactiveUI.Primitives.Async;

/// <summary>
/// Provides factory methods for creating observable sequences that are generated by invoking a specified function each
/// time a new observer subscribes.
/// </summary>
/// <remarks>Nothing runs at declaration: the factory is called once per subscriber, so each one gets a sequence built
/// from the state that holds at its own subscribe time.</remarks>
public static partial class SignalAsync
{
    /// <summary>Creates a new observable sequence for each subscription by invoking the specified asynchronous factory function.</summary>
    /// <typeparam name="T">The type of the elements produced by the observable sequence.</typeparam>
    /// <param name="factory">A function that receives a cancellation token and returns a task that produces an observable sequence to
    /// subscribe to.</param>
    /// <returns>An observable sequence that awaits <paramref name="factory"/> on each subscribe and subscribes to
    /// whatever it yields.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static IObservableAsync<T> Defer<T>(Func<CancellationToken, ValueTask<IObservableAsync<T>>> factory) =>
        new DeferAsyncSignalAsync<T>(factory);

    /// <summary>
    /// Returns an observable sequence that is created by invoking the specified factory function each time a new
    /// observer subscribes.
    /// </summary>
    /// <typeparam name="T">The type of the elements produced by the observable sequence.</typeparam>
    /// <param name="factory">A function that returns a new instance of an observable sequence to be subscribed to for each observer.</param>
    /// <returns>An observable sequence that calls <paramref name="factory"/> on each subscribe and subscribes to
    /// whatever it returns.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static IObservableAsync<T> Defer<T>(Func<IObservableAsync<T>> factory) =>
        new DeferSyncSignalAsync<T>(factory);

    /// <summary>Backs <see cref="Defer{T}(Func{IObservableAsync{T}})"/>: each subscribe calls the factory and hands the
    /// wrapped observer to the sequence it returns.</summary>
    /// <typeparam name="T">The element type.</typeparam>
    /// <param name="factory">The deferred factory invoked once per subscribe.</param>
    internal sealed class DeferSyncSignalAsync<T>(Func<IObservableAsync<T>> factory) : IObservableAsync<T>
    {
        /// <inheritdoc/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        ValueTask<IAsyncDisposable> IObservableAsync<T>.SubscribeAsync(
            IObserverAsync<T> observer,
            CancellationToken cancellationToken) =>
            factory().SubscribeAsync(observer.Wrap(), cancellationToken);
    }

    /// <summary>Backs the <see cref="ValueTask"/>-returning
    /// <see cref="Defer{T}(Func{CancellationToken, ValueTask{IObservableAsync{T}}})"/>, awaiting the factory before it
    /// can subscribe.</summary>
    /// <typeparam name="T">The element type.</typeparam>
    /// <param name="factory">The deferred factory invoked once per subscribe.</param>
    internal sealed class DeferAsyncSignalAsync<T>(Func<CancellationToken, ValueTask<IObservableAsync<T>>> factory) : IObservableAsync<T>
    {
        /// <inheritdoc/>
        async ValueTask<IAsyncDisposable> IObservableAsync<T>.SubscribeAsync(
            IObserverAsync<T> observer,
            CancellationToken cancellationToken)
        {
            var signal = await factory(cancellationToken).ConfigureAwait(false);
            return await signal.SubscribeAsync(observer.Wrap(), cancellationToken).ConfigureAwait(false);
        }
    }
}
