// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ReactiveUI.Primitives.SystemReactiveBridge.Generator;

/// <summary>Emits opt-in System.Reactive.Async bridge extensions when async Rx symbols are visible to the consumer compilation.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class SystemReactiveAsyncBridgeGenerator : IIncrementalGenerator
{
    /// <summary>Attribute source emitted during post initialization so consumers can identify generated async bridge output.</summary>
    private const string MarkerSource = """
// <auto-generated />
[assembly: global::ReactiveUI.Primitives.SystemReactiveBridge.Generated.PrimitivesSystemReactiveAsyncBridgeGeneratedAttribute("0.1.0")]

namespace ReactiveUI.Primitives.SystemReactiveBridge.Generated;

[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
internal sealed class PrimitivesSystemReactiveAsyncBridgeGeneratedAttribute : global::System.Attribute
{
    public PrimitivesSystemReactiveAsyncBridgeGeneratedAttribute(string generatorVersion) => GeneratorVersion = generatorVersion;

    public string GeneratorVersion { get; }
}
""";

    /// <summary>Bridge extension source emitted when the consumer compilation references System.Reactive.Async and ReactiveUI.Primitives.Async.</summary>
    private const string BridgeSource = """
// <auto-generated />
#nullable enable
namespace ReactiveUI.Primitives.SystemReactiveBridge;

/// <summary>
/// Adapter methods emitted only for compilations that already reference System.Reactive.Async and ReactiveUI.Primitives.Async.
/// </summary>
internal static class SystemReactiveAsyncObservableBridge
{
    /// <summary>
    /// Wraps a System.Reactive.Async observable as a ReactiveUI.Primitives.Async observable.
    /// </summary>
    public static global::ReactiveUI.Primitives.Async.IObservableAsync<T> AsPrimitivesAsyncObservable<T>(
        this global::System.IAsyncObservable<T> source)
    {
        if (source == null)
        {
            throw new global::System.ArgumentNullException(nameof(source));
        }

        return new SystemAsyncObservableToPrimitivesObservable<T>(source);
    }

    /// <summary>
    /// Wraps a ReactiveUI.Primitives.Async observable as a System.Reactive.Async observable.
    /// </summary>
    public static global::System.IAsyncObservable<T> AsSystemReactiveAsyncObservable<T>(
        this global::ReactiveUI.Primitives.Async.IObservableAsync<T> source)
    {
        if (source == null)
        {
            throw new global::System.ArgumentNullException(nameof(source));
        }

        return new PrimitivesObservableToSystemAsyncObservable<T>(source);
    }

    /// <summary>
    /// Wraps a System.Reactive.Async observer as a ReactiveUI.Primitives.Async observer.
    /// </summary>
    public static global::ReactiveUI.Primitives.Async.IObserverAsync<T> AsPrimitivesAsyncObserver<T>(
        this global::System.IAsyncObserver<T> observer)
    {
        if (observer == null)
        {
            throw new global::System.ArgumentNullException(nameof(observer));
        }

        return new SystemAsyncObserverToPrimitivesObserver<T>(observer);
    }

    /// <summary>
    /// Wraps a ReactiveUI.Primitives.Async observer as a System.Reactive.Async observer.
    /// </summary>
    public static global::System.IAsyncObserver<T> AsSystemReactiveAsyncObserver<T>(
        this global::ReactiveUI.Primitives.Async.IObserverAsync<T> observer)
    {
        if (observer == null)
        {
            throw new global::System.ArgumentNullException(nameof(observer));
        }

        return new PrimitivesObserverToSystemAsyncObserver<T>(observer);
    }

    private sealed class SystemAsyncObservableToPrimitivesObservable<T>(global::System.IAsyncObservable<T> source)
        : global::ReactiveUI.Primitives.Async.SignalAsync<T>
    {
        protected override global::System.Threading.Tasks.ValueTask<global::System.IAsyncDisposable> SubscribeAsyncCore(
            global::ReactiveUI.Primitives.Async.IObserverAsync<T> observer,
            global::System.Threading.CancellationToken cancellationToken)
        {
            if (observer == null)
            {
                throw new global::System.ArgumentNullException(nameof(observer));
            }

            if (cancellationToken.IsCancellationRequested)
            {
                return new global::System.Threading.Tasks.ValueTask<global::System.IAsyncDisposable>(
                    global::ReactiveUI.Primitives.Async.Disposables.DisposableAsync.Empty);
            }

            return SubscribeCoreAsync(source, observer, cancellationToken);
        }

        private static async global::System.Threading.Tasks.ValueTask<global::System.IAsyncDisposable> SubscribeCoreAsync(
            global::System.IAsyncObservable<T> source,
            global::ReactiveUI.Primitives.Async.IObserverAsync<T> observer,
            global::System.Threading.CancellationToken cancellationToken)
        {
            var subscription = await source.SubscribeAsync(new SystemAsyncToPrimitivesForwarder<T>(observer, cancellationToken))
                .ConfigureAwait(false);

            if (!cancellationToken.IsCancellationRequested)
            {
                return subscription;
            }

            await subscription.DisposeAsync().ConfigureAwait(false);
            return global::ReactiveUI.Primitives.Async.Disposables.DisposableAsync.Empty;
        }
    }

    private sealed class PrimitivesObservableToSystemAsyncObservable<T>(
        global::ReactiveUI.Primitives.Async.IObservableAsync<T> source)
        : global::System.IAsyncObservable<T>
    {
        public global::System.Threading.Tasks.ValueTask<global::System.IAsyncDisposable> SubscribeAsync(
            global::System.IAsyncObserver<T> observer)
        {
            if (observer == null)
            {
                throw new global::System.ArgumentNullException(nameof(observer));
            }

            return source.SubscribeAsync(new SystemAsyncObserverToPrimitivesObserver<T>(observer), global::System.Threading.CancellationToken.None);
        }
    }

    private sealed class SystemAsyncObserverToPrimitivesObserver<T>(global::System.IAsyncObserver<T> observer)
        : global::ReactiveUI.Primitives.Async.IObserverAsync<T>
    {
        public global::System.Threading.Tasks.ValueTask OnNextAsync(
            T value,
            global::System.Threading.CancellationToken cancellationToken) =>
            cancellationToken.IsCancellationRequested ? default : observer.OnNextAsync(value);

        public global::System.Threading.Tasks.ValueTask OnErrorResumeAsync(
            global::System.Exception error,
            global::System.Threading.CancellationToken cancellationToken) =>
            cancellationToken.IsCancellationRequested ? default : observer.OnErrorAsync(error);

        public global::System.Threading.Tasks.ValueTask OnCompletedAsync(global::ReactiveUI.Primitives.Result result) =>
            result.IsFailure ? observer.OnErrorAsync(GetResultException(result.Exception)) : observer.OnCompletedAsync();

        public global::System.Threading.Tasks.ValueTask DisposeAsync() => default;
    }

    private sealed class PrimitivesObserverToSystemAsyncObserver<T>(
        global::ReactiveUI.Primitives.Async.IObserverAsync<T> observer)
        : global::System.IAsyncObserver<T>
    {
        public global::System.Threading.Tasks.ValueTask OnNextAsync(T value) =>
            observer.OnNextAsync(value, global::System.Threading.CancellationToken.None);

        public global::System.Threading.Tasks.ValueTask OnErrorAsync(global::System.Exception error) =>
            observer.OnCompletedAsync(global::ReactiveUI.Primitives.Result.Failure(error));

        public global::System.Threading.Tasks.ValueTask OnCompletedAsync() =>
            observer.OnCompletedAsync(global::ReactiveUI.Primitives.Result.Success);
    }

    private sealed class SystemAsyncToPrimitivesForwarder<T>(
        global::ReactiveUI.Primitives.Async.IObserverAsync<T> observer,
        global::System.Threading.CancellationToken cancellationToken)
        : global::System.IAsyncObserver<T>
    {
        public global::System.Threading.Tasks.ValueTask OnNextAsync(T value) =>
            cancellationToken.IsCancellationRequested ? default : observer.OnNextAsync(value, cancellationToken);

        public global::System.Threading.Tasks.ValueTask OnErrorAsync(global::System.Exception error) =>
            cancellationToken.IsCancellationRequested
                ? default
                : observer.OnCompletedAsync(global::ReactiveUI.Primitives.Result.Failure(error));

        public global::System.Threading.Tasks.ValueTask OnCompletedAsync() =>
            cancellationToken.IsCancellationRequested
                ? default
                : observer.OnCompletedAsync(global::ReactiveUI.Primitives.Result.Success);
    }

    private static global::System.Exception GetResultException(global::System.Exception? exception) =>
        exception ?? new global::System.InvalidOperationException("A failed asynchronous observable result did not include an exception.");
}
""";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource(
                "PrimitivesSystemReactiveAsyncBridgeGeneratedAttribute.g.cs",
                SourceText.From(MarkerSource, Encoding.UTF8)));

        context.RegisterSourceOutput(context.CompilationProvider, static (output, compilation) =>
        {
            if (compilation.GetTypeByMetadataName("System.IAsyncObservable`1") is null ||
                compilation.GetTypeByMetadataName("System.IAsyncObserver`1") is null ||
                compilation.GetTypeByMetadataName("ReactiveUI.Primitives.Async.IObservableAsync`1") is null ||
                compilation.GetTypeByMetadataName("ReactiveUI.Primitives.Async.IObserverAsync`1") is null)
            {
                return;
            }

            output.AddSource("SystemReactiveAsyncObservableBridge.g.cs", SourceText.From(BridgeSource, Encoding.UTF8));
        });
    }
}
