// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ReactiveUI.Primitives.SystemReactiveBridge.Generator;

/// <summary>
/// Emits opt-in System.Reactive-shaped bridge extensions when System.Reactive symbols are visible to the consumer compilation.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SystemReactiveBridgeGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Attribute source emitted during post initialization so consumers can identify generated bridge output.
    /// </summary>
    private const string MarkerSource = """
// <auto-generated />
[assembly: global::ReactiveUI.Primitives.SystemReactiveBridge.Generated.PrimitivesSystemReactiveBridgeGeneratedAttribute("0.1.0")]

namespace ReactiveUI.Primitives.SystemReactiveBridge.Generated;

[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
internal sealed class PrimitivesSystemReactiveBridgeGeneratedAttribute : global::System.Attribute
{
    public PrimitivesSystemReactiveBridgeGeneratedAttribute(string generatorVersion) => GeneratorVersion = generatorVersion;

    public string GeneratorVersion { get; }
}
""";

    /// <summary>
    /// Bridge extension source emitted when the consumer compilation references System.Reactive.
    /// </summary>
    private const string SignalBridgeSource = """
// <auto-generated />
#nullable enable
namespace ReactiveUI.Primitives.SystemReactiveBridge;

/// <summary>
/// Adapter methods emitted only for compilations that already reference System.Reactive.
/// </summary>
internal static class SystemReactiveSignalBridge
{
    /// <summary>
    /// Treats any System.Reactive/BCL observable as a Primitives signal source.
    /// </summary>
    public static global::System.IObservable<T> AsPrimitivesSignal<T>(this global::System.IObservable<T> source)
    {
        if (source == null)
        {
            throw new global::System.ArgumentNullException(nameof(source));
        }

        return source;
    }

    /// <summary>
    /// Exposes a Primitives signal as a System.Reactive-compatible observable without adding a production dependency.
    /// </summary>
    public static global::System.IObservable<T> AsSystemObservable<T>(this global::System.IObservable<T> source)
    {
        if (source == null)
        {
            throw new global::System.ArgumentNullException(nameof(source));
        }

        return source;
    }
}
""";

    /// <summary>
    /// Scheduler bridge source emitted when the consumer compilation references System.Reactive scheduler types.
    /// </summary>
    private const string SchedulerBridgeSource = """
// <auto-generated />
#nullable enable
namespace ReactiveUI.Primitives.SystemReactiveBridge;

/// <summary>
/// Scheduler adapter methods emitted only for compilations that already reference System.Reactive.
/// </summary>
internal static class SystemReactiveSchedulerBridge
{
    /// <summary>
    /// Wraps a System.Reactive scheduler as a ReactiveUI.Primitives sequencer.
    /// </summary>
    public static global::ReactiveUI.Primitives.Concurrency.ISequencer AsSequencer(this global::System.Reactive.Concurrency.IScheduler scheduler)
    {
        if (scheduler == null)
        {
            throw new global::System.ArgumentNullException(nameof(scheduler));
        }

        return scheduler is SequencerScheduler adapter ? adapter.Sequencer : new SchedulerSequencer(scheduler);
    }

    /// <summary>
    /// Wraps a ReactiveUI.Primitives sequencer as a System.Reactive scheduler.
    /// </summary>
    public static global::System.Reactive.Concurrency.IScheduler AsSystemScheduler(this global::ReactiveUI.Primitives.Concurrency.ISequencer sequencer)
    {
        if (sequencer == null)
        {
            throw new global::System.ArgumentNullException(nameof(sequencer));
        }

        return sequencer is SchedulerSequencer adapter ? adapter.Scheduler : new SequencerScheduler(sequencer);
    }

    private sealed class SchedulerSequencer : global::ReactiveUI.Primitives.Concurrency.ISequencer
    {
        private readonly global::System.Reactive.Concurrency.IScheduler _inner;

        public SchedulerSequencer(global::System.Reactive.Concurrency.IScheduler inner) => _inner = inner;

        public global::System.Reactive.Concurrency.IScheduler Scheduler => _inner;

        public global::System.DateTimeOffset Now => _inner.Now;

        public long Timestamp => _inner.Now.UtcTicks;

        public void Schedule(global::ReactiveUI.Primitives.Concurrency.IWorkItem item)
        {
            if (item == null)
            {
                throw new global::System.ArgumentNullException(nameof(item));
            }

            _inner.Schedule(item, static (_, workItem) => Execute(workItem));
        }

        public void Schedule(global::ReactiveUI.Primitives.Concurrency.IWorkItem item, long dueTimestamp)
        {
            if (item == null)
            {
                throw new global::System.ArgumentNullException(nameof(item));
            }

            _inner.Schedule(item, TimeUntil(dueTimestamp), static (_, workItem) => Execute(workItem));
        }

        private global::System.TimeSpan TimeUntil(long dueTimestamp)
        {
            var timestamp = Timestamp;
            if (dueTimestamp <= timestamp)
            {
                return global::System.TimeSpan.Zero;
            }

            var ticks = dueTimestamp - timestamp;
            return ticks >= global::System.TimeSpan.MaxValue.Ticks
                ? global::System.TimeSpan.MaxValue
                : global::System.TimeSpan.FromTicks(ticks);
        }

        private static global::System.IDisposable Execute(global::ReactiveUI.Primitives.Concurrency.IWorkItem item)
        {
            if (item is global::ReactiveUI.Primitives.Disposables.IsDisposed { IsDisposed: true })
            {
                return global::ReactiveUI.Primitives.Disposables.Disposable.Empty;
            }

            item.Execute();
            return global::ReactiveUI.Primitives.Disposables.Disposable.Empty;
        }
    }

    private sealed class SequencerScheduler : global::System.Reactive.Concurrency.IScheduler
    {
        private readonly global::ReactiveUI.Primitives.Concurrency.ISequencer _inner;

        public SequencerScheduler(global::ReactiveUI.Primitives.Concurrency.ISequencer inner) => _inner = inner;

        public global::ReactiveUI.Primitives.Concurrency.ISequencer Sequencer => _inner;

        public global::System.DateTimeOffset Now => _inner.Now;

        public global::System.IDisposable Schedule<TState>(TState state, global::System.Func<global::System.Reactive.Concurrency.IScheduler, TState, global::System.IDisposable> action)
        {
            if (action == null)
            {
                throw new global::System.ArgumentNullException(nameof(action));
            }

            var item = new SchedulerWorkItem<TState>(this, state, action);
            _inner.Schedule(item);
            return item;
        }

        public global::System.IDisposable Schedule<TState>(
            TState state,
            global::System.TimeSpan dueTime,
            global::System.Func<global::System.Reactive.Concurrency.IScheduler, TState, global::System.IDisposable> action)
        {
            if (action == null)
            {
                throw new global::System.ArgumentNullException(nameof(action));
            }

            var item = new SchedulerWorkItem<TState>(this, state, action);
            var normalized = Normalize(dueTime);
            if (normalized == global::System.TimeSpan.Zero)
            {
                _inner.Schedule(item);
            }
            else
            {
                _inner.Schedule(item, AddTimestamp(_inner.Timestamp, normalized));
            }

            return item;
        }

        public global::System.IDisposable Schedule<TState>(
            TState state,
            global::System.DateTimeOffset dueTime,
            global::System.Func<global::System.Reactive.Concurrency.IScheduler, TState, global::System.IDisposable> action)
        {
            if (action == null)
            {
                throw new global::System.ArgumentNullException(nameof(action));
            }

            return Schedule(state, dueTime - Now, action);
        }
    }

    private sealed class SchedulerWorkItem<TState> : global::ReactiveUI.Primitives.Concurrency.IWorkItem, global::ReactiveUI.Primitives.Disposables.IsDisposed
    {
        private readonly global::System.Reactive.Concurrency.IScheduler _scheduler;
        private readonly TState _state;
        private readonly global::System.Func<global::System.Reactive.Concurrency.IScheduler, TState, global::System.IDisposable> _action;
        private global::System.IDisposable? _disposable;
        private int _isDisposed;

        public SchedulerWorkItem(
            global::System.Reactive.Concurrency.IScheduler scheduler,
            TState state,
            global::System.Func<global::System.Reactive.Concurrency.IScheduler, TState, global::System.IDisposable> action)
        {
            _scheduler = scheduler;
            _state = state;
            _action = action;
        }

        public bool IsDisposed => global::System.Threading.Volatile.Read(ref _isDisposed) != 0;

        public void Dispose()
        {
            if (global::System.Threading.Interlocked.Exchange(ref _isDisposed, 1) != 0)
            {
                return;
            }

            global::System.Threading.Interlocked.Exchange(ref _disposable, global::ReactiveUI.Primitives.Disposables.Disposable.Empty)?.Dispose();
        }

        public void Execute()
        {
            if (IsDisposed)
            {
                return;
            }

            var disposable = _action(_scheduler, _state) ?? global::ReactiveUI.Primitives.Disposables.Disposable.Empty;
            var previous = global::System.Threading.Interlocked.CompareExchange(ref _disposable, disposable, null);
            if (previous != null)
            {
                disposable.Dispose();
                return;
            }

            if (!IsDisposed)
            {
                return;
            }

            disposable.Dispose();
        }
    }

    private static global::System.TimeSpan Normalize(global::System.TimeSpan timeSpan) =>
        timeSpan.Ticks < 0 ? global::System.TimeSpan.Zero : timeSpan;

    private static long AddTimestamp(long timestamp, global::System.TimeSpan dueTime)
    {
        var delta = ToTimestampDelta(dueTime);
        if (delta == 0)
        {
            return timestamp;
        }

        return long.MaxValue - timestamp < delta ? long.MaxValue : timestamp + delta;
    }

    private static long ToTimestampDelta(global::System.TimeSpan dueTime)
    {
        var normalized = Normalize(dueTime);
        if (normalized == global::System.TimeSpan.Zero)
        {
            return 0;
        }

        var ticks = normalized.TotalSeconds * global::System.Diagnostics.Stopwatch.Frequency;
        if (ticks >= long.MaxValue)
        {
            return long.MaxValue;
        }

        return global::System.Math.Max(1, (long)global::System.Math.Ceiling(ticks));
    }
}
""";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource(
                "PrimitivesSystemReactiveBridgeGeneratedAttribute.g.cs",
                SourceText.From(MarkerSource, Encoding.UTF8)));

        context.RegisterSourceOutput(context.CompilationProvider, static (output, compilation) =>
        {
            if (compilation.GetTypeByMetadataName("System.Reactive.Linq.Observable") == null)
            {
                return;
            }

            output.AddSource("SystemReactiveSignalBridge.g.cs", SourceText.From(SignalBridgeSource, Encoding.UTF8));
        });

        context.RegisterSourceOutput(context.CompilationProvider, static (output, compilation) =>
        {
            if (compilation.GetTypeByMetadataName("System.Reactive.Concurrency.IScheduler") == null)
            {
                return;
            }

            output.AddSource("SystemReactiveSchedulerBridge.g.cs", SourceText.From(SchedulerBridgeSource, Encoding.UTF8));
        });
    }
}
