<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(WinUITargetFrameworks)</TargetFrameworks>
    <UseWinUI>true</UseWinUI>
    <AppxGeneratePriEnabled Condition="'$(OS)' != 'Windows_NT'">false</AppxGeneratePriEnabled>
    <IncludePriFilesOutputGroup Condition="'$(OS)' != 'Windows_NT'">false</IncludePriFilesOutputGroup>
    <IncludeProjectPriFile Condition="'$(OS)' != 'Windows_NT'">false</IncludeProjectPriFile>
    <PackageDescription>WinUI dispatcher queue integration sequencers for ReactiveUI.Primitives.</PackageDescription>
    <PackageTags>system.reactive;rx;reactive;primitives;winui;dispatcher-queue;scheduler;sequencer</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <ProjectReference Include="..\ReactiveUI.Primitives\ReactiveUI.Primitives.csproj" />
  </ItemGroup>

</Project>
