<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(WindowsLibraryTargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <UseWPF>true</UseWPF>
    <PackageDescription>WPF integration sequencers for ReactiveUI.Primitives.</PackageDescription>
    <PackageTags>system.reactive;rx;reactive;primitives;wpf;dispatcher;scheduler;sequencer</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReactiveUI.Primitives\ReactiveUI.Primitives.csproj" />
  </ItemGroup>

</Project>
