// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ReactiveUI.Primitives.R3Bridge.Generator;

/// <summary>Emits opt-in R3Async-shaped bridge extensions when R3Async symbols are visible to the consumer compilation.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class R3AsyncBridgeGenerator : IIncrementalGenerator
{
    /// <summary>Async bridge source emitted when the consumer compilation references R3Async and ReactiveUI.Primitives.Async.</summary>
    private const string BridgeSource = """
        // <auto-generated />
        #nullable enable
        namespace ReactiveUI.Primitives.R3Bridge;
        
        /// <summary>
        /// Async adapter methods emitted only for compilations that already reference R3Async and ReactiveUI.Primitives.Async.
        /// </summary>
        internal static class R3AsyncObservableBridge
        {
            /// <summary>
            /// Wraps an R3Async observable as a ReactiveUI.Primitives.Async observable.
            /// </summary>
            public static global::ReactiveUI.Primitives.Async.IObservableAsync<T> AsPrimitivesAsyncObservable<T>(
                this global::R3Async.AsyncObservable<T> source)
            {
                if (source == null)
                {
                    throw new global::System.ArgumentNullException(nameof(source));
                }
        
                return new R3AsyncToPrimitivesObservable<T>(source);
            }
        
            /// <summary>
            /// Wraps a ReactiveUI.Primitives.Async observable as an R3Async observable using the consumer's R3Async package.
            /// </summary>
            public static global::R3Async.AsyncObservable<T> AsR3AsyncObservable<T>(
                this global::ReactiveUI.Primitives.Async.IObservableAsync<T> source)
            {
                if (source == null)
                {
                    throw new global::System.ArgumentNullException(nameof(source));
                }
        
                return new PrimitivesToR3AsyncObservable<T>(source);
            }
        
            private sealed class R3AsyncToPrimitivesObservable<T>(global::R3Async.AsyncObservable<T> source)
                : global::ReactiveUI.Primitives.Async.SignalAsync<T>
            {
                protected override global::System.Threading.Tasks.ValueTask<global::System.IAsyncDisposable> SubscribeAsyncCore(
                    global::ReactiveUI.Primitives.Async.IObserverAsync<T> observer,
                    global::System.Threading.CancellationToken cancellationToken)
                {
                    if (observer == null)
                    {
                        throw new global::System.ArgumentNullException(nameof(observer));
                    }
        
                    return source.SubscribeAsync(new R3AsyncToPrimitivesObserver<T>(observer), cancellationToken);
                }
            }
        
            private sealed class R3AsyncToPrimitivesObserver<T>(global::ReactiveUI.Primitives.Async.IObserverAsync<T> observer)
                : global::R3Async.AsyncObserver<T>
            {
                protected override global::System.Threading.Tasks.ValueTask OnNextAsyncCore(
                    T value,
                    global::System.Threading.CancellationToken cancellationToken) =>
                    observer.OnNextAsync(value, cancellationToken);
        
                protected override global::System.Threading.Tasks.ValueTask OnErrorResumeAsyncCore(
                    global::System.Exception error,
                    global::System.Threading.CancellationToken cancellationToken) =>
                    observer.OnErrorResumeAsync(error, cancellationToken);
        
                protected override global::System.Threading.Tasks.ValueTask OnCompletedAsyncCore(global::R3Async.Result result) =>
                    observer.OnCompletedAsync(ToPrimitivesResult(result));
            }
        
            private sealed class PrimitivesToR3AsyncObservable<T>(global::ReactiveUI.Primitives.Async.IObservableAsync<T> source)
                : global::R3Async.AsyncObservable<T>
            {
                protected override global::System.Threading.Tasks.ValueTask<global::System.IAsyncDisposable> SubscribeAsyncCore(
                    global::R3Async.AsyncObserver<T> observer,
                    global::System.Threading.CancellationToken cancellationToken)
                {
                    if (observer == null)
                    {
                        throw new global::System.ArgumentNullException(nameof(observer));
                    }
        
                    return source.SubscribeAsync(new PrimitivesToR3AsyncObserver<T>(observer), cancellationToken);
                }
            }
        
            private sealed class PrimitivesToR3AsyncObserver<T>(global::R3Async.AsyncObserver<T> observer)
                : global::ReactiveUI.Primitives.Async.IObserverAsync<T>
            {
                public global::System.Threading.Tasks.ValueTask OnNextAsync(
                    T value,
                    global::System.Threading.CancellationToken cancellationToken) =>
                    observer.OnNextAsync(value, cancellationToken);
        
                public global::System.Threading.Tasks.ValueTask OnErrorResumeAsync(
                    global::System.Exception error,
                    global::System.Threading.CancellationToken cancellationToken) =>
                    observer.OnErrorResumeAsync(error, cancellationToken);
        
                public global::System.Threading.Tasks.ValueTask OnCompletedAsync(global::ReactiveUI.Primitives.Result result) =>
                    observer.OnCompletedAsync(ToR3AsyncResult(result));
        
                public global::System.Threading.Tasks.ValueTask DisposeAsync() => observer.DisposeAsync();
            }
        
            private static global::ReactiveUI.Primitives.Result ToPrimitivesResult(global::R3Async.Result result) =>
                result.IsFailure
                    ? global::ReactiveUI.Primitives.Result.Failure(GetResultException(result.Exception))
                    : global::ReactiveUI.Primitives.Result.Success;
        
            private static global::R3Async.Result ToR3AsyncResult(global::ReactiveUI.Primitives.Result result) =>
                result.IsFailure
                    ? global::R3Async.Result.Failure(GetResultException(result.Exception))
                    : global::R3Async.Result.Success;
        
            private static global::System.Exception GetResultException(global::System.Exception? exception) =>
                exception ?? new global::System.InvalidOperationException("A failed asynchronous observable result did not include an exception.");
        }
        """;

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterSourceOutput(context.CompilationProvider, static (output, compilation) =>
        {
            if (compilation.GetTypeByMetadataName("R3Async.AsyncObservable`1") is null ||
                compilation.GetTypeByMetadataName("R3Async.AsyncObserver`1") is null ||
                compilation.GetTypeByMetadataName("R3Async.Result") is null ||
                compilation.GetTypeByMetadataName("ReactiveUI.Primitives.Async.IObservableAsync`1") is null)
            {
                return;
            }

            output.AddSource("R3AsyncObservableBridge.g.cs", SourceText.From(BridgeSource, Encoding.UTF8));
        });
}
