// Copyright (c) 2019-2026 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ReactiveUI.Primitives.R3Bridge.Generator;

    /// <summary>Emits opt-in R3-shaped bridge extensions when R3 symbols are visible to the consumer compilation.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class R3BridgeGenerator : IIncrementalGenerator
{
    /// <summary>Attribute source emitted during post initialization so consumers can identify generated bridge output.</summary>
    private const string MarkerSource = """
// <auto-generated />
[assembly: global::ReactiveUI.Primitives.R3Bridge.Generated.PrimitivesR3BridgeGeneratedAttribute("0.1.0")]

namespace ReactiveUI.Primitives.R3Bridge.Generated;

[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
internal sealed class PrimitivesR3BridgeGeneratedAttribute : global::System.Attribute
{
    public PrimitivesR3BridgeGeneratedAttribute(string generatorVersion) => GeneratorVersion = generatorVersion;

    public string GeneratorVersion { get; }
}
""";

    /// <summary>Bridge extension source emitted when the consumer compilation references R3.</summary>
    private const string BridgeSource = """
// <auto-generated />
#nullable enable
namespace ReactiveUI.Primitives.R3Bridge;

/// <summary>
/// Adapter methods emitted only for compilations that already reference R3.
/// </summary>
internal static class R3SignalBridge
{
    /// <summary>
    /// Wraps an R3 observable as a Primitives/BCL observable source.
    /// </summary>
    public static global::System.IObservable<T> AsPrimitivesSignal<T>(this global::R3.Observable<T> source)
    {
        if (source == null)
        {
            throw new global::System.ArgumentNullException(nameof(source));
        }

        return global::ReactiveUI.Primitives.Signals.Signal.Create<T>(observer => source.Subscribe(new R3ToPrimitivesObserver<T>(observer)));
    }

    /// <summary>
    /// Wraps a Primitives signal as an R3 observable using the consumer's R3 package.
    /// </summary>
    public static global::R3.Observable<T> AsR3Observable<T>(this global::System.IObservable<T> source)
    {
        if (source == null)
        {
            throw new global::System.ArgumentNullException(nameof(source));
        }

        return global::R3.Observable.Create<T>(observer => source.Subscribe(new PrimitivesToR3Observer<T>(observer)));
    }

    private sealed class R3ToPrimitivesObserver<T> : global::R3.Observer<T>
    {
        private readonly global::System.IObserver<T> _observer;

        public R3ToPrimitivesObserver(global::System.IObserver<T> observer) => _observer = observer;

        protected override void OnNextCore(T value) => _observer.OnNext(value);

        protected override void OnErrorResumeCore(global::System.Exception error) => _observer.OnError(error);

        protected override void OnCompletedCore(global::R3.Result result)
        {
            if (result.IsFailure)
            {
                _observer.OnError(result.Exception);
                return;
            }

            _observer.OnCompleted();
        }
    }

    private sealed class PrimitivesToR3Observer<T> : global::System.IObserver<T>
    {
        private readonly global::R3.Observer<T> _observer;

        public PrimitivesToR3Observer(global::R3.Observer<T> observer) => _observer = observer;

        public void OnNext(T value) => _observer.OnNext(value);

        public void OnError(global::System.Exception error) => _observer.OnCompleted(global::R3.Result.Failure(error));

        public void OnCompleted() => _observer.OnCompleted(global::R3.Result.Success);
    }
}
""";

    /// <summary>Async bridge source emitted when the consumer compilation references R3 and ReactiveUI.Primitives.Async.</summary>
    private const string AsyncBridgeSource = """
// <auto-generated />
#nullable enable
namespace ReactiveUI.Primitives.R3Bridge;

/// <summary>
/// Async adapter methods emitted only for compilations that already reference R3 and ReactiveUI.Primitives.Async.
/// </summary>
internal static class R3AsyncBridge
{
    /// <summary>
    /// Wraps an R3 observable as a ReactiveUI.Primitives.Async observable.
    /// </summary>
    public static global::ReactiveUI.Primitives.Async.IObservableAsync<T> AsPrimitivesAsyncObservable<T>(this global::R3.Observable<T> source)
    {
        if (source == null)
        {
            throw new global::System.ArgumentNullException(nameof(source));
        }

        return global::ReactiveUI.Primitives.Async.SignalAsync.Create<T>((observer, cancellationToken) =>
            new global::System.Threading.Tasks.ValueTask<global::System.IAsyncDisposable>(
                new AsyncDisposableAdapter(source.Subscribe(new R3ToAsyncObserver<T>(observer, cancellationToken)))));
    }

    /// <summary>
    /// Wraps a ReactiveUI.Primitives.Async observable as an R3 observable using the consumer's R3 package.
    /// </summary>
    public static global::R3.Observable<T> AsR3Observable<T>(this global::ReactiveUI.Primitives.Async.IObservableAsync<T> source)
    {
        if (source == null)
        {
            throw new global::System.ArgumentNullException(nameof(source));
        }

        return global::R3.Observable.Create<T>(observer =>
        {
            var subscriptionTask = SubscribeAndCaptureAsync(source, observer, global::System.Threading.CancellationToken.None);
            return new DisposableSubscription(subscriptionTask);
        });
    }

    private sealed class R3ToAsyncObserver<T>(
        global::ReactiveUI.Primitives.Async.IObserverAsync<T> observer,
        global::System.Threading.CancellationToken cancellationToken) : global::R3.Observer<T>
    {
        protected override void OnNextCore(T value) => RunSynchronously(observer.OnNextAsync(value, cancellationToken));

        protected override void OnErrorResumeCore(global::System.Exception error) =>
            RunSynchronously(observer.OnErrorResumeAsync(error, cancellationToken));

        protected override void OnCompletedCore(global::R3.Result result)
        {
            var asyncResult = result.IsFailure
                ? global::ReactiveUI.Primitives.Async.Result.Failure(result.Exception)
                : global::ReactiveUI.Primitives.Async.Result.Success;
            RunSynchronously(observer.OnCompletedAsync(asyncResult));
        }
    }

    private sealed class AsyncToR3Observer<T>(global::R3.Observer<T> observer)
        : global::ReactiveUI.Primitives.Async.IObserverAsync<T>
    {
        public global::System.Threading.Tasks.ValueTask OnNextAsync(T value, global::System.Threading.CancellationToken cancellationToken)
        {
            observer.OnNext(value);
            return default;
        }

        public global::System.Threading.Tasks.ValueTask OnErrorResumeAsync(
            global::System.Exception error,
            global::System.Threading.CancellationToken cancellationToken)
        {
            observer.OnErrorResume(error);
            return default;
        }

        public global::System.Threading.Tasks.ValueTask OnCompletedAsync(global::ReactiveUI.Primitives.Async.Result result)
        {
            observer.OnCompleted(result.IsFailure
                ? global::R3.Result.Failure(result.Exception)
                : global::R3.Result.Success);
            return default;
        }

        public global::System.Threading.Tasks.ValueTask DisposeAsync() => default;
    }

    private sealed class AsyncDisposableAdapter(global::System.IDisposable disposable) : global::System.IAsyncDisposable
    {
        public global::System.Threading.Tasks.ValueTask DisposeAsync()
        {
            disposable.Dispose();
            return default;
        }
    }

    private sealed class DisposableSubscription(
        global::System.Threading.Tasks.Task<global::System.IAsyncDisposable?> subscriptionTask) : global::System.IDisposable
    {
        private int _disposed;

        public void Dispose()
        {
            if (global::System.Threading.Interlocked.Exchange(ref _disposed, 1) != 0)
            {
                return;
            }

            _ = DisposeAsync();
        }

        private async global::System.Threading.Tasks.Task DisposeAsync()
        {
            try
            {
                var subscription = await subscriptionTask.ConfigureAwait(false);
                if (subscription is not null)
                {
                    await subscription.DisposeAsync().ConfigureAwait(false);
                }
            }
            catch (global::System.OperationCanceledException)
            {
            }
        }
    }

    private static async global::System.Threading.Tasks.Task<global::System.IAsyncDisposable?> SubscribeAndCaptureAsync<T>(
        global::ReactiveUI.Primitives.Async.IObservableAsync<T> source,
        global::R3.Observer<T> observer,
        global::System.Threading.CancellationToken cancellationToken)
    {
        try
        {
            return await source.SubscribeAsync(new AsyncToR3Observer<T>(observer), cancellationToken).ConfigureAwait(false);
        }
        catch (global::System.OperationCanceledException)
        {
            return null;
        }
        catch (global::System.Exception error)
        {
            observer.OnCompleted(global::R3.Result.Failure(error));
            return null;
        }
    }

    private static void RunSynchronously(global::System.Threading.Tasks.ValueTask task)
    {
        try
        {
            if (task.IsCompletedSuccessfully)
            {
                task.GetAwaiter().GetResult();
                return;
            }

            task.AsTask().GetAwaiter().GetResult();
        }
        catch (global::System.OperationCanceledException)
        {
        }
    }
}
""";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource(
                "PrimitivesR3BridgeGeneratedAttribute.g.cs",
                SourceText.From(MarkerSource, Encoding.UTF8)));

        context.RegisterSourceOutput(context.CompilationProvider, static (output, compilation) =>
        {
            if (compilation.GetTypeByMetadataName("R3.Observable`1") is null)
            {
                return;
            }

            output.AddSource("R3SignalBridge.g.cs", SourceText.From(BridgeSource, Encoding.UTF8));
        });

        context.RegisterSourceOutput(context.CompilationProvider, static (output, compilation) =>
        {
            if (compilation.GetTypeByMetadataName("R3.Observable`1") is null ||
                compilation.GetTypeByMetadataName("ReactiveUI.Primitives.Async.IObservableAsync`1") is null)
            {
                return;
            }

            output.AddSource("R3AsyncBridge.g.cs", SourceText.From(AsyncBridgeSource, Encoding.UTF8));
        });
    }
}
