<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LibraryTargetFrameworks)</TargetFrameworks>
    <RootNamespace>ReactiveUI.Primitives.OccasionallyConnected.Storage.Sqlite</RootNamespace>
    <PackageDescription>SQLite storage primitives for durable, occasionally connected reactive streams.</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SQLitePCLRaw.core" />
    <PackageReference Include="SQLite3MC.PCLRaw.bundle" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\OccasionallyConnected.Sqlite.Shared\*.cs" Link="Sqlite\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReactiveUI.Primitives.OccasionallyConnected.Core\ReactiveUI.Primitives.OccasionallyConnected.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="README.md" />
  </ItemGroup>
</Project>
